[workspace]
members = [
  "starsector-mod-info",
  "starsector-mod-info-storage",
  "starsector-mod-info-shared",
  "starsector-mod-info-auth",
]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
